# =====================================================
# Kustomization Base
# =====================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

resources:
  - backend.yaml
  - configmap.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: devops-learning
  app.kubernetes.io/managed-by: kustomize
